steps:
  - name: hashicorp/packer:1.13
    entrypoint: packer
    args:
      - init
      - "main.pkr.hcl"

  - name: hashicorp/packer:1.13
    entrypoint: packer
    args:
      - build
      - -var
      - "project_id=$_PROJECT_ID"
      - -var
      - "zone=$_ZONE"
      - -var
      - "webapp_git_repo_url=$_WEBAPP_GIT_REPO_URL"
      - -var
      - "webapp_git_sha=$_WEBAPP_GIT_SHA"
      - -var
      - "packer_vm_sa_email=$_PACKER_VM_SA_EMAIL"
      - .

options:
  logging: CLOUD_LOGGING_ONLY
